import { StyleSheet } from "react-native";
import Fonts from "./Fonts";
export const styles = StyleSheet.create({
    body: {
      flex: 1,
      backgroundColor: "#1F2022",
    },
    topRow: {
      alignSelf: "center",
      alignContent: "center",
      flexDirection: "row",
      width: "100%",
      height: "6%",
      backgroundColor: "#25282F",
    },
    monthContainer: {
      // alignItems:"center",
      //alignContent:"center",
      width: "40%",
      alignSelf: "center",
      backgroundColor: "transparent",
      flexDirection: "row",
      left: "5%",
      alignContent:"center",
      alignItems:"center",
    },
    monthText: {
      alignSelf: "center",
      fontSize: Fonts.medium,
      color: "white",
    },
    arrowIcon: {
      width: Fonts.small,
      height: Fonts.small,
      alignSelf: "center",
      tintColor: "white",
    },
    iconsRow: {
      width: "35%",
      height: "100%",
      backgroundColor: "transparent",
      alignSelf: "center",
      alignContent: "center",
      flexDirection: "row",
      alignItems:"center",
    },
    topIcons: {
      width: Fonts.regular,
      height: Fonts.regular,
      alignSelf: "center",
      tintColor: "white",
      marginRight: "20%",
    },
    viewCategory: {
        width:"100%",
        height:"4%",
        backgroundColor:"#25282F",
        flexDirection: "row",
        alignItems:"center",
        borderBottomColor:"#34373e",
        borderBottomWidth:1,
        //gap: 10,
        justifyContent: "space-between",
    },
    viewOption: {
        backgroundColor:"transparent",
        width:"20%",
        height:"100%",
        alignContent: "center",
        alignItems:"center",
        borderBottomColor: "#fd6557",
        borderBottomWidth:0,
    },
    viewOptionTitle: {
        color:"#7c7d84",
        fontSize:Fonts.medium,
        fontWeight:600,
    },
    mainBalances:{
        width: "100%",
        height:"7%",
        backgroundColor:"red",
        flexDirection: "row",
        justifyContent: "space-evenly",
        backgroundColor:"#25282F",
        borderBottomColor:"#34373e",
        borderBottomWidth:1,
    },
    mainBalancesChild:{
        width: "25%",
        height: "90%",
        backgroundColor: "transparent",
        alignItems:"center",
        alignSelf:"center",
        justifyContent:"center",

    },
    mainBalancesTitle:{
        color:"#fafbfb",
        fontSize:Fonts.small,
    },
    mainBalancesSubtitle:{
        fontSize: Fonts.small,
        fontWeight:400,
    },
    bodyTransactions:{
        flex:1,
        justifyContent:"center",
        alignItems:"center",
    },
    floatingTransactions:{
        width: Fonts.extraLarge,
        height:Fonts.extraLarge,
        borderWidth: 1,
        borderColor: "#fd6557",
        borderRadius:100,
        backgroundColor: "#fd6557",
        position: "absolute",
        top: "90%",
        left: "83%",
        justifyContent:"center",
    },
    floatingNotes:{
        width: Fonts.extraLarge,
        height: Fonts.extraLarge,
        borderWidth: 1,
        borderColor: "#393a3f",
        borderRadius:100,
        backgroundColor: "#393a3f",
        position: "absolute",
        top: "90%",
        left: "65%",
        justifyContent:"center",
    },
    transactionsContainer:{
        backgroundColor:"transparent",
        width:"100%",
        height:"100%",
    },
    modalCategory:{
        backgroundColor:"#27282d",
        width:"100%",
        height:"23.5%",
        alignContent:"center",
        borderBottomWidth:1,
        borderColor:"#34373e",
    },
    transactionTopBar:{
      width:"90%",
      height:"100%",
      backgroundColor:"transparent",
      alignSelf:"center",
      alignContent:"center",
      flexDirection:"row",
      alignItems:"center",
      justifyContent:"flex-start",
    },
    transactionDayContainer:{
      backgroundColor:"#fe7a6e",
      height:"50%",
      width:"12.5%",
      left:"15%",
      justifyContent:"center",
      alignItems:"center",
      alignSelf:"center",
      borderRadius:6,
    },  
    transactionDetails:{
      backgroundColor:"#27282d",
      width:"100%",
      height:"100%",
      flexDirection:"row",
      alignItems:"center",
      justifyContent:"flex-start",
    },  
  });
  