import { StyleSheet } from "react-native";
import Fonts from "./Fonts";

export const styles = StyleSheet.create({
    body: {
      flex:1,
      backgroundColor: "#25282F",
    },
    header: {
      width: "100%",
      height: "5%",
      backgroundColor: "transparent",
      flexDirection: "row",
      justifyContent: "space-between",
    },
    headerLeft: {
      width: "30%",
      height: "100%",
      backgroundColor: "transparent",
      alignItems: "center",
      justifyContent: "space-evenly",
      flexDirection: "row",
    },
    headerTitle: {
      color: "white",
      fontSize:Fonts.regular,
      left: 15,
    },
    headerRight: {
      width: "15%",
      height: "100%",
      backgroundColor: "transparent",
      justifyContent: "center",
      alignItems: "center",
    },
    categoriesBody: {
      top:"2.5%",
      width: "95%",
      height: "5%",
      backgroundColor: "transparent",
      justifyContent: "space-around",
      flexDirection: "row",
      alignItems: "center",
      alignSelf:"center",
    },
    category: {
      width: "31%",
      height: "70%",
      backgroundColor: "#181818",
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      borderColor: "#181818",
      borderWidth: 1,
    },
    categoryTitle: {
      color: "#b0b1b5",
      fontSize: Fonts.medium,
      fontWeight: 500,
    },
    formBody: {
      width: "90%",
      height: "30%",
      backgroundColor: "transparent",
      alignSelf: "center",
      top: "3%",
      justifyContent: "space-between",
      
    },
    formRow: {
      width: "100%",
      height: "17%",
      backgroundColor: "transparent",
      alignContent: "center",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
  
    },
    formRowTitle: {
      fontSize: Fonts.medium,
      color: "#b0b1b5",
      fontWeight: 400,
    },
    formItem: {
      width: "70%",
      height: "100%",
      borderBottomWidth: 0.3,
      borderColor: "#36373c",
      justifyContent: "center",
      alignItems: "flex-start",
    },
    formItemText: {
      color: "white",
      fontSize: Fonts.regular,
      fontWeight: "400",
      width:"100%",
    },
    divider: {
      height:"1.5%",
      backgroundColor:"#212226",
      top:"5.2%",
      borderColor:"#36373c",
      borderBottomWidth:1,
      borderTopWidth:1,
    },
    descriptionBody:{
      width:"90%",
      height:"5%",
      backgroundColor:"transparent",
      top:"14%",
      alignSelf:"center",
      justifyContent:"space-between",
      alignItems:"center",
      
      borderBottomWidth:0.3,
      borderColor:"#36373c",
      flexDirection:"row",
    },
    buttonsContainer:{
      width:"100%",
      height:"10%",
      backgroundColor:"transparent",
      top:"20%",
      flexDirection:"row",
      justifyContent:"space-around",
      alignItems:"center",
    },
    saveButton:{
        width:"67%",
        height:"60%",
        backgroundColor:"#52a3ff",
        alignItems:"center",
        justifyContent:"center",
        borderRadius:18,
    },
    continueButton:{
      width:"25%",
      height:"60%",
      backgroundColor:"#27282d",
      alignItems:"center",
      justifyContent:"center",
      borderRadius:18,
      borderColor:"#6c6d71",
      borderWidth:1,
    },
  });
  